"""db_1_0_0 initial version

Revision ID: 090dfcf0e4de
Revises: 
Create Date: 2020-10-11 18:46:04.474732

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '090dfcf0e4de'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricultural_type',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agricultural_type'))
    )
    op.create_table('contact_submission',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_submission'))
    )
    op.create_index(op.f('ix_contact_submission_email'), 'contact_submission', ['email'], unique=False)
    op.create_table('country',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country'))
    )
    op.create_index(op.f('ix_country_iso3'), 'country', ['iso3'], unique=True)
    op.create_table('group',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_name', sa.Unicode(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('group_name', name=op.f('uq_group_group_name')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('newsletter_subscribe',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(name='is_active'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_subscribe'))
    )
    op.create_index(op.f('ix_newsletter_subscribe_email'), 'newsletter_subscribe', ['email'], unique=True)
    op.create_table('plan_execution_group',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_execution_group'))
    )
    op.create_table('role',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('soil_type',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('yield_modifier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soil_type'))
    )
    op.create_table('unit',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('so_unit', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit'))
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(name='active'), nullable=False),
    sa.Column('confirmed_at', backend.database.types.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('crop_type',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('botanical_title', sa.String(length=128), nullable=False),
    sa.Column('so_id', sa.String(length=16), nullable=False),
    sa.Column('icc_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_crop_type_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_type'))
    )
    op.create_table('external_identity',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('external_id', sa.Unicode(length=255), nullable=False),
    sa.Column('external_user_name', sa.Unicode(length=255), nullable=True),
    sa.Column('local_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.Unicode(length=50), nullable=False),
    sa.Column('access_token', sa.Unicode(length=512), nullable=True),
    sa.Column('alt_token', sa.Unicode(length=512), nullable=True),
    sa.Column('token_secret', sa.Unicode(length=512), nullable=True),
    sa.ForeignKeyConstraint(['local_user_id'], ['user.id'], name=op.f('fk_external_identity_local_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('external_id', 'local_user_id', 'provider_name', name='pk_external_identity'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('group_permission',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_permission_group_id_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'perm_name', name='pk_group_permission'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('region',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('so_code', sa.String(length=4), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_region_country_id_country')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region'))
    )
    op.create_table('resource',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.Unicode(length=100), nullable=False),
    sa.Column('resource_type', sa.Unicode(length=30), nullable=False),
    sa.Column('owner_group_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_group_id'], ['group.id'], name=op.f('fk_resource_owner_group_id_group'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], name=op.f('fk_resource_owner_user_id_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['resource.resource_id'], name=op.f('fk_resource_parent_id_resource'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_resource')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resource_owner_group_id'), 'resource', ['owner_group_id'], unique=False)
    op.create_index(op.f('ix_resource_owner_user_id'), 'resource', ['owner_user_id'], unique=False)
    op.create_table('user_group',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_user_group_group_id_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_group_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_user_group')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_permission',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_permission_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'perm_name', name='pk_user_permission'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_role_id_role')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_role_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role'))
    )
    op.create_table('country_crop',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_type_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('fk_country_crop_country_id_country')),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_type.id'], name=op.f('fk_country_crop_crop_type_id_crop_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_country_crop'))
    )
    op.create_table('crop_type_region',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('crop_type_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['crop_type_id'], ['crop_type.id'], name=op.f('fk_crop_type_region_crop_type_id_crop_type'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_crop_type_region_region_id_region'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('crop_type_id', 'region_id', name=op.f('pk_crop_type_region'))
    )
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resource.resource_id'], name=op.f('fk_farm_id_resource'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name=op.f('fk_farm_region_id_region'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('group_resource_permission',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_resource_permission_group_id_group'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], name=op.f('fk_group_resource_permission_resource_id_resource'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'resource_id', 'perm_name', name='pk_group_resource_permission'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resource.resource_id'], name=op.f('fk_plan_id_resource'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_resource_permission',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('perm_name', sa.Unicode(length=64), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], name=op.f('fk_user_resource_permission_resource_id_resource'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_resource_permission_user_id_user'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', 'perm_name', name='pk_user_resource_permission'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_task',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('start_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.Unicode(length=100), nullable=False),
    sa.Column('task_type', sa.Unicode(length=30), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_task_plan_id_plan'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_plan_task')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('season',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('start_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('farm_id', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', backend.database.types.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_season_farm_id_farm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season'))
    )
    op.create_table('plan_task_general',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan_task.task_id'], name=op.f('fk_plan_task_general_id_plan_task'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_task_general')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_task_harvesting',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crop_yield', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['plan_task.task_id'], name=op.f('fk_plan_task_harvesting_id_plan_task'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_task_harvesting')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('reference_parcel',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('ancestor_id', sa.BigInteger(), nullable=True),
    sa.Column('season_id', sa.BigInteger(), nullable=True),
    sa.Column('parcel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('parcel_name', sa.Unicode(length=100), nullable=False),
    sa.Column('parcel_type', sa.Unicode(length=30), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['reference_parcel.parcel_id'], name=op.f('fk_reference_parcel_ancestor_id_reference_parcel')),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name=op.f('fk_reference_parcel_season_id_season'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parcel_id', name=op.f('pk_reference_parcel')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('agricultural_parcel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['reference_parcel.parcel_id'], name=op.f('fk_agricultural_parcel_id_reference_parcel'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agricultural_parcel')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('physical_block',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('eligible_area', sa.Float(), nullable=False),
    sa.Column('soil_type_id', sa.BigInteger(), nullable=False),
    sa.Column('agricultural_type_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agricultural_type_id'], ['agricultural_type.id'], name=op.f('fk_physical_block_agricultural_type_id_agricultural_type')),
    sa.ForeignKeyConstraint(['id'], ['reference_parcel.parcel_id'], name=op.f('fk_physical_block_id_reference_parcel'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soil_type_id'], ['soil_type.id'], name=op.f('fk_physical_block_soil_type_id_soil_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_physical_block')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('reference_parcel_relation',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('parcel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['reference_parcel.parcel_id'], name=op.f('fk_reference_parcel_relation_block_id_reference_parcel'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['reference_parcel.parcel_id'], name=op.f('fk_reference_parcel_relation_parcel_id_reference_parcel'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('block_id', 'parcel_id', name=op.f('pk_reference_parcel_relation'))
    )
    op.create_table('plan_execution',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('agricultural_parcel_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', backend.database.types.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agricultural_parcel_id'], ['agricultural_parcel.id'], name=op.f('fk_plan_execution_agricultural_parcel_id_agricultural_parcel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['plan_execution_group.id'], name=op.f('fk_plan_execution_group_id_plan_execution_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_execution_plan_id_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_execution'))
    )
    op.create_table('execution_task',
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('Deleted', 'Pending', 'Completed', 'Archived', name='taskstatus'), nullable=False),
    sa.Column('start_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('plan_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_task_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.Unicode(length=100), nullable=False),
    sa.Column('task_type', sa.Unicode(length=30), nullable=False),
    sa.ForeignKeyConstraint(['plan_execution_id'], ['plan_execution.id'], name=op.f('fk_execution_task_plan_execution_id_plan_execution'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_task_id'], ['plan_task.task_id'], name=op.f('fk_execution_task_plan_task_id_plan_task'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_execution_task')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('execution_task_general',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['execution_task.task_id'], name=op.f('fk_execution_task_general_id_execution_task'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_task_general')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('execution_task_harvesting',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crop_yield', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['execution_task.task_id'], name=op.f('fk_execution_task_harvesting_id_execution_task'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_task_harvesting')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('execution_task_harvesting')
    op.drop_table('execution_task_general')
    op.drop_table('execution_task')
    op.drop_table('plan_execution')
    op.drop_table('reference_parcel_relation')
    op.drop_table('physical_block')
    op.drop_table('agricultural_parcel')
    op.drop_table('reference_parcel')
    op.drop_table('plan_task_harvesting')
    op.drop_table('plan_task_general')
    op.drop_table('season')
    op.drop_table('plan_task')
    op.drop_table('user_resource_permission')
    op.drop_table('plan')
    op.drop_table('group_resource_permission')
    op.drop_table('farm')
    op.drop_table('crop_type_region')
    op.drop_table('country_crop')
    op.drop_table('user_role')
    op.drop_table('user_permission')
    op.drop_table('user_group')
    op.drop_index(op.f('ix_resource_owner_user_id'), table_name='resource')
    op.drop_index(op.f('ix_resource_owner_group_id'), table_name='resource')
    op.drop_table('resource')
    op.drop_table('region')
    op.drop_table('group_permission')
    op.drop_table('external_identity')
    op.drop_table('crop_type')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('unit')
    op.drop_table('soil_type')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_table('plan_execution_group')
    op.drop_index(op.f('ix_newsletter_subscribe_email'), table_name='newsletter_subscribe')
    op.drop_table('newsletter_subscribe')
    op.drop_table('group')
    op.drop_index(op.f('ix_country_iso3'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_contact_submission_email'), table_name='contact_submission')
    op.drop_table('contact_submission')
    op.drop_table('agricultural_type')
    # ### end Alembic commands ###
