"""season reference one to many

Revision ID: 0fed690a57ce
Revises: 844a430e8494
Create Date: 2020-09-09 13:45:13.937550

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa
import backend
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fed690a57ce'
down_revision = '844a430e8494'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_reference_parcel')
    op.add_column('reference_parcel', sa.Column('season_id', sa.BigInteger(), nullable=True))
    op.drop_index('idx_reference_parcel_geometry', table_name='reference_parcel')
    op.create_foreign_key(op.f('fk_reference_parcel_season_id_season'), 'reference_parcel', 'season', ['season_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reference_parcel_season_id_season'), 'reference_parcel', type_='foreignkey')
    op.create_index('idx_reference_parcel_geometry', 'reference_parcel', ['geometry'], unique=False)
    op.drop_column('reference_parcel', 'season_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('season_reference_parcel',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('season_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reference_parcel_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reference_parcel_id'], ['reference_parcel.parcel_id'], name='fk_season_reference_parcel_reference_parcel_id_reference_parcel', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name='fk_season_reference_parcel_season_id_season', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id', 'reference_parcel_id', name='pk_season_reference_parcel')
    )
    # ### end Alembic commands ###
