"""Payment Order model fixed

Revision ID: 872c786f22b8
Revises: 98f50ac105ad
Create Date: 2020-01-22 17:28:17.427185

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '872c786f22b8'
down_revision = '98f50ac105ad'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'download_cnt',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'download_cnt',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
