"""Payment Order and StripeUser many to one added

Revision ID: 9327b873d98c
Revises: 872c786f22b8
Create Date: 2020-01-22 17:43:25.847807

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '9327b873d98c'
down_revision = '872c786f22b8'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_order_user_id_stripe_user'), 'order', 'stripe_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_user_id_stripe_user'), 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###
