"""minor fixes

Revision ID: d7cd5138bb9b
Revises: 0fed690a57ce
Create Date: 2020-09-18 07:56:14.159782

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = 'd7cd5138bb9b'
down_revision = '0fed690a57ce'
branch_labels = ()
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_harvesting',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('specific_product_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task.task_id'], name=op.f('fk_task_harvesting_id_task'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specific_product_id'], ['specific_product.id'], name=op.f('fk_task_harvesting_specific_product_id_specific_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_harvesting')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('task_harvesting')
    # ### end Alembic commands ###
