"""Add cover photo to category model

Revision ID: e7d08dff6efa
Revises: 42d7fa594797
Create Date: 2020-01-18 17:47:26.218793

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = 'e7d08dff6efa'
down_revision = '42d7fa594797'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('cover', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'cover')
    # ### end Alembic commands ###
